import { Inter } from "next/font/google"
import { ReactDO } from "react"
import Link from "next/link"
import "./globals.css";




import Navbar from "./components/navbar/navbar.js"
import Home from "./page.js"
import YourLibrary from "./library/page.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quizify!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="bg-beige">
        {/* Show top div for screen sizes greater than small */}
        <div className="hidden lg:flex flex-col w-full min-h-screen relative">
          <Navbar />
          {children}
        </div>

        {/* Show bottom div for screen sizes less than small */}
        <div className="lg:hidden text-5xl font-mono text-btn-200 p-14 flex text-center items-center align-middle w-full min-h-screen relative">
          Please transition to a larger viewing screen
        </div>
      </body>
    </html>
  );
}
