import { Inter } from "next/font/google"
import { React } from "react"
import Link from "next/link"
import "./globals.css";



import Navbar from "./components/navbar/navbar.js"
import Home from "./page.js"
import YourLibrary from "./library/page.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QUIZIFY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
        <body className={"bg-beige "}>
          <div className="w-full min-h-screen flex flex-col relative">
            <Navbar />
            {children}

          </div>

        </body>

    </html>
  );
}
