import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page.js";
import Navbar from "./navbar/navbar.js";
import Domain from "./components/domain.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QUIZIFYY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="bg-yellow-300">
        <div className="w-full min-h-screen flex flex-col relative">
          <Navbar />
          <div className = "flex flex-row"> 
            <div className = "flex flex-row"> 
              <Domain title={"Function Groups"} description={"Lorem Ipsum"} author={"Devin"} />
            </div>
            <div className = "flex flex-row">
              <Domain title={"Function Groups"} description={"Lorem Ipsum"} author={"Devin"} />
            </div>

          </div>
        </div>
      </body>
    </html>
  );
}
